var OAuth;null==OAuth&&(OAuth={});OAuth.setProperties=function(a,c){if(null!=a&&null!=c)for(var b in c)a[b]=c[b];return a};
OAuth.setProperties(OAuth,{percentEncode:function(a){if(null==a)return"";if(a instanceof Array){for(var c="";0<a.length;++a)""!=c&&(c+="&"),c+=OAuth.percentEncode(a[0]);return c}a=encodeURIComponent(a);a=a.replace(/\!/g,"%21");a=a.replace(/\*/g,"%2A");a=a.replace(/\'/g,"%27");a=a.replace(/\(/g,"%28");return a=a.replace(/\)/g,"%29")},decodePercent:function(a){null!=a&&(a=a.replace(/\+/g," "));return decodeURIComponent(a)},getParameterList:function(a){if(null==a)return[];if("object"!=typeof a)return OAuth.decodeForm(a+
"");if(a instanceof Array)return a;var c=[],b;for(b in a)c.push([b,a[b]]);return c},getParameterMap:function(a){if(null==a)return{};if("object"!=typeof a)return OAuth.getParameterMap(OAuth.decodeForm(a+""));if(a instanceof Array){for(var c={},b=0;b<a.length;++b){var d=a[b][0];void 0===c[d]&&(c[d]=a[b][1])}return c}return a},getParameter:function(a,c){if(a instanceof Array)for(var b=0;b<a.length;++b){if(a[b][0]==c)return a[b][1]}else return OAuth.getParameterMap(a)[c];return null},formEncode:function(a){for(var c=
"",a=OAuth.getParameterList(a),b=0;b<a.length;++b){var d=a[b][1];null==d&&(d="");""!=c&&(c+="&");c+=OAuth.percentEncode(a[b][0])+"="+OAuth.percentEncode(d)}return c},decodeForm:function(a){for(var c=[],a=a.split("&"),b=0;b<a.length;++b){var d=a[b];if(""!=d){var e=d.indexOf("="),f;0>e?(f=OAuth.decodePercent(d),d=null):(f=OAuth.decodePercent(d.substring(0,e)),d=OAuth.decodePercent(d.substring(e+1)));c.push([f,d])}}return c},setParameter:function(a,c,b){var d=a.parameters;if(d instanceof Array){for(a=
0;a<d.length;++a)d[a][0]==c&&(void 0===b?d.splice(a,1):(d[a][1]=b,b=void 0));void 0!==b&&d.push([c,b])}else d=OAuth.getParameterMap(d),d[c]=b,a.parameters=d},setParameters:function(a,c){for(var b=OAuth.getParameterList(c),d=0;d<b.length;++d)OAuth.setParameter(a,b[d][0],b[d][1])},completeRequest:function(a,c){null==a.method&&(a.method="GET");var b=OAuth.getParameterMap(a.parameters);null==b.oauth_consumer_key&&OAuth.setParameter(a,"oauth_consumer_key",c.consumerKey||"");null==b.oauth_token&&null!=
c.token&&OAuth.setParameter(a,"oauth_token",c.token);null==b.oauth_version&&OAuth.setParameter(a,"oauth_version","1.0");null==b.oauth_timestamp&&OAuth.setParameter(a,"oauth_timestamp",OAuth.timestamp());null==b.oauth_nonce&&OAuth.setParameter(a,"oauth_nonce",OAuth.nonce(6));OAuth.SignatureMethod.sign(a,c)},setTimestampAndNonce:function(a){OAuth.setParameter(a,"oauth_timestamp",OAuth.timestamp());OAuth.setParameter(a,"oauth_nonce",OAuth.nonce(6))},addToURL:function(a,c){newURL=a;if(null!=c){var b=
OAuth.formEncode(c);0<b.length&&(newURL=0>a.indexOf("?")?newURL+"?":newURL+"&",newURL+=b)}return newURL},getAuthorizationHeader:function(a,c){for(var b='OAuth realm="'+OAuth.percentEncode(a)+'"',d=OAuth.getParameterList(c),e=0;e<d.length;++e){var f=d[e],g=f[0];0==g.indexOf("oauth_")&&(b+=","+OAuth.percentEncode(g)+'="'+OAuth.percentEncode(f[1])+'"')}return b},correctTimestampFromSrc:function(a){var a=a||"oauth_timestamp",c=document.getElementsByTagName("script");if(null!=c&&c.length&&(c=c[c.length-
1].src)){var b=c.indexOf("?");0>b||(parameters=OAuth.getParameterMap(OAuth.decodeForm(c.substring(b+1))),a=parameters[a],null!=a&&OAuth.correctTimestamp(a))}},correctTimestamp:function(a){OAuth.timeCorrectionMsec=1E3*a-(new Date).getTime()},timeCorrectionMsec:0,timestamp:function(){var a=(new Date).getTime()+OAuth.timeCorrectionMsec;return Math.floor(a/1E3)},nonce:function(a){for(var c=OAuth.nonce.CHARS,b="",d=0;d<a;++d)var e=Math.floor(Math.random()*c.length),b=b+c.substring(e,e+1);return b}});
OAuth.nonce.CHARS="0123456789ABCDEFGHIJKLMNOPQRSTUVWXTZabcdefghiklmnopqrstuvwxyz";OAuth.declareClass=function(a,c,b){var d=a[c];a[c]=b;if(null!=b&&null!=d)for(var e in d)"prototype"!=e&&(b[e]=d[e]);return b};OAuth.declareClass(OAuth,"SignatureMethod",function(){});
OAuth.setProperties(OAuth.SignatureMethod.prototype,{sign:function(a){var c=this.getSignature(OAuth.SignatureMethod.getBaseString(a));OAuth.setParameter(a,"oauth_signature",c);return c},initialize:function(a,c){var b;b=null!=c.accessorSecret&&9<a.length&&"-Accessor"==a.substring(a.length-9)?c.accessorSecret:c.consumerSecret;this.key=OAuth.percentEncode(b)+"&"+OAuth.percentEncode(c.tokenSecret)}});
OAuth.setProperties(OAuth.SignatureMethod,{sign:function(a,c){var b=OAuth.getParameterMap(a.parameters).oauth_signature_method;if(null==b||""==b)b="HMAC-SHA1",OAuth.setParameter(a,"oauth_signature_method",b);OAuth.SignatureMethod.newMethod(b,c).sign(a)},newMethod:function(a,c){var b=OAuth.SignatureMethod.REGISTERED[a];if(null!=b){var d=new b;d.initialize(a,c);return d}var b=Error("signature_method_rejected"),e="";for(d in OAuth.SignatureMethod.REGISTERED)""!=e&&(e+="&"),e+=OAuth.percentEncode(d);
b.oauth_acceptable_signature_methods=e;throw b;},REGISTERED:{},registerMethodClass:function(a,c){for(var b=0;b<a.length;++b)OAuth.SignatureMethod.REGISTERED[a[b]]=c},makeSubclass:function(a){var c=OAuth.SignatureMethod,b=function(){c.call(this)};b.prototype=new c;b.prototype.getSignature=a;return b.prototype.constructor=b},getBaseString:function(a){var c=a.action,b=c.indexOf("?");if(0>b)b=a.parameters;else for(var b=OAuth.decodeForm(c.substring(b+1)),d=OAuth.getParameterList(a.parameters),e=0;e<d.length;++e)b.push(d[e]);
return OAuth.percentEncode(a.method.toUpperCase())+"&"+OAuth.percentEncode(OAuth.SignatureMethod.normalizeUrl(c))+"&"+OAuth.percentEncode(OAuth.SignatureMethod.normalizeParameters(b))},normalizeUrl:function(a){var c=OAuth.SignatureMethod.parseUri(a),a=c.protocol.toLowerCase(),b=c.authority.toLowerCase();if("http"==a&&80==c.port||"https"==a&&443==c.port){var d=b.lastIndexOf(":");0<=d&&(b=b.substring(0,d))}(c=c.path)||(c="/");return a+"://"+b+c},parseUri:function(a){for(var c="source,protocol,authority,userInfo,user,password,host,port,relative,path,directory,file,query,anchor".split(","),
a=/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@\/]*):?([^:@\/]*))?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/.exec(a),b={},d=14;d--;)b[c[d]]=a[d]||"";return b},normalizeParameters:function(a){if(null==a)return"";for(var c=OAuth.getParameterList(a),a=[],b=0;b<c.length;++b){var d=c[b];"oauth_signature"!=d[0]&&a.push([OAuth.percentEncode(d[0])+" "+OAuth.percentEncode(d[1]),d])}a.sort(function(a,b){return a[0]<b[0]?-1:a[0]>b[0]?1:0});c=[];for(b=0;b<a.length;++b)c.push(a[b][1]);
return OAuth.formEncode(c)}});OAuth.SignatureMethod.registerMethodClass(["PLAINTEXT","PLAINTEXT-Accessor"],OAuth.SignatureMethod.makeSubclass(function(){return this.key}));OAuth.SignatureMethod.registerMethodClass(["HMAC-SHA1","HMAC-SHA1-Accessor"],OAuth.SignatureMethod.makeSubclass(function(a){b64pad="=";return b64_hmac_sha1(this.key,a)}));try{OAuth.correctTimestampFromSrc()}catch(e$$1){};