Ti.include("/helpers/sha1.js");Ti.include("/helpers/oauth.js");
var OAuthAdapter=function(x,y,z){Ti.API.info("*********************************************");Ti.API.info("If you like the OAuth Adapter, consider donating at");Ti.API.info("https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=T5HUU4J5EQTJU&lc=IT&item_name=OAuth%20Adapter&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted");Ti.API.info("*********************************************");var n=null,r=null,s=null,f=null,i=null,j={consumerSecret:x,tokenSecret:""},t=[],h=null,
g=null,l=null,k=null,m=null,u=null;this.loadAccessToken=function(a){Ti.API.debug("Loading access token for service ["+a+"].");u=a;a=Ti.Filesystem.getFile(Ti.Filesystem.applicationDataDirectory,a+".config");if(!1!=a.exists&&(a=a.read(),null!=a)){try{var b=JSON.parse(a.text)}catch(c){return}b.accessToken&&(f=b.accessToken);b.accessTokenSecret&&(i=b.accessTokenSecret);Ti.API.debug("Loading access token: done [accessToken:"+f+"][accessTokenSecret:"+i+"].")}};this.removeAccessToken=function(a){Ti.API.debug("Removing access token ["+
a+"].");i=f=null;this.saveAccessToken(a);Ti.API.debug("Removing access token : done.")};this.saveAccessToken=function(a){Ti.API.debug("Saving access token ["+a+"].");var b=Ti.Filesystem.getFile(Ti.Filesystem.applicationDataDirectory,a+".config");null==b&&(b=Ti.Filesystem.createFile(Ti.Filesystem.applicationDataDirectory,a+".config"));b.write(JSON.stringify({accessToken:f,accessTokenSecret:i}));Ti.API.debug("Saving access token: done.")};this.isAuthorized=function(){return!(null==f||null==i)};var o=
function(a){a={action:a,method:"POST",parameters:[]};a.parameters.push(["oauth_consumer_key",y]);a.parameters.push(["oauth_signature_method",z]);return a};this.getPin=function(){return n};this.getRequestToken=function(a){j.tokenSecret="";var b=o(a);OAuth.setTimestampAndNonce(b);OAuth.SignatureMethod.sign(b,j);var c=Ti.Network.createHTTPClient();c.open("POST",a,!1);c.send(OAuth.getParameterMap(b.parameters));a=OAuth.getParameterMap(c.responseText);r=a.oauth_token;s=a.oauth_token_secret;Ti.API.debug("request token got the following response: "+
c.responseText);return c.responseText};var p=function(){Ti.API.debug("destroyAuthorizeUI");if(null!=h)try{Ti.API.debug("destroyAuthorizeUI:webView.removeEventListener"),l.removeEventListener("load",v),Ti.API.debug("destroyAuthorizeUI:window.close()"),h.close(),Ti.API.debug("destroyAuthorizeUI:window.remove(view)"),h.remove(g),Ti.API.debug("destroyAuthorizeUI:view.remove(webView)"),g.remove(l),Ti.API.debug("destroyAuthorizeUI:nullifying"),h=g=l=null}catch(a){Ti.API.debug("Cannot destroy the authorize UI. Ignoring.")}},
v=function(a){Ti.API.debug("authorizeUILoaded");Ti.API.debug(a.source.html);var b=a.source.html.indexOf("<code>"),b=a.source.html.substring(b+6,b+30);if((b=b.substring(0,b.indexOf("</code>")))&&0<b.length)n=b,k&&setTimeout(function(){m?k.call(m):k()},100),c=d=null,p();else{b=Ti.XML.parseString(a.source.html);a=b.getElementsByTagName("div");for(b=0;b<a.length;b++){var c=a.item(b),d=c.attributes.getNamedItem("id");if(d&&"oauth_pin"==d.nodeValue){n=c.text;k&&setTimeout(function(){m?k.call(m):k()},100);
c=d=null;p();break}}b=a=null}};this.showAuthorizeUI=function(a,b,c){try{k=b;m=c;h=Ti.UI.createWindow({});var d=Ti.UI.create2DMatrix().scale(0);g=Ti.UI.createView({top:5,width:310,height:350,border:10,backgroundColor:"white",borderColor:"#aaa",borderRadius:20,borderWidth:5,zIndex:-1,transform:d});closeLabel=Ti.UI.createLabel({textAlign:"right",font:{fontWeight:"bold",fontSize:"12pt"},text:"(X)",top:10,right:12,height:14});require("/ui/common/globals").openmodal(h);l=Ti.UI.createWebView({top:20,url:a,
autoDetect:[Ti.UI.AUTODETECT_NONE]});Ti.API.debug("Setting:["+Ti.UI.AUTODETECT_NONE+"]");l.addEventListener("load",v);g.add(l);closeLabel.addEventListener("click",p);g.add(closeLabel);h.add(g);var f=Ti.UI.createAnimation();f.transform=Ti.UI.create2DMatrix();f.duration=500;g.animate(f)}catch(i){Titanium.API.debug(i)}};this.getAccessToken=function(a){j.tokenSecret=s;var b=o(a);b.parameters.push(["oauth_token",r]);b.parameters.push(["oauth_verifier",n]);OAuth.setTimestampAndNonce(b);OAuth.SignatureMethod.sign(b,
j);var b=OAuth.getParameterMap(b.parameters),c;for(c in b)Ti.API.debug(c+": "+b[c]);c=Ti.Network.createHTTPClient();c.open("POST",a,!1);c.send(b);a=OAuth.getParameterMap(c.responseText);f=a.oauth_token;i=a.oauth_token_secret;Ti.API.debug("*** get access token, Response: "+c.responseText);for(Ti.API.debug("Processing queue.");null!=(q=t.shift());)w(q.url,q.parameters,q.title,q.successMessage,q.errorMessage);Ti.API.debug("Processing queue: done.");return c.responseText};var w=function(a,b,c,d,g){Ti.API.debug("Sending a message to the service at ["+
a+"] with the following params: "+JSON.stringify(b));if(null==f||null==i)Ti.API.debug("The send status cannot be processed as the client doesn't have an access token. The status update will be sent as soon as the client has an access token."),t.push({url:a,parameters:b,title:c,successMessage:d,errorMessage:g});else{j.tokenSecret=i;var h=o(a);h.parameters.push(["oauth_token",f]);for(e in b)h.parameters.push(b[e]);OAuth.setTimestampAndNonce(h);OAuth.SignatureMethod.sign(h,j);var b=OAuth.getParameterMap(h.parameters),
e;for(e in b)Ti.API.debug(e+": "+b[e]);e=Ti.Network.createHTTPClient();e.open("POST",a,!1);e.send(b);200==e.status?null!=d&&("function"===typeof d?d.call(this,e.status,e.responseText):Ti.UI.createAlertDialog({title:c,message:d}).show()):401==e.status?this.removeAccessToken(u):null!=g&&("function"===typeof g?g.call(this,e.status,e.responseText):Ti.UI.createAlertDialog({title:c,message:g}).show());Ti.API.debug("*** sendStatus, Response: ["+e.status+"] "+e.responseText);return e.responseText}};this.send=
w;this.sendraw=function(a,b){if(null==f||null==i)return null;j.tokenSecret=i;var c=o(a);c.parameters.push(["oauth_token",f]);for(d in b)c.parameters.push(b[d]);OAuth.setTimestampAndNonce(c);OAuth.SignatureMethod.sign(c,j);var c=OAuth.getParameterMap(c.parameters),d;for(d in c)Ti.API.debug(d+": "+c[d]);d=Ti.Network.createHTTPClient();d.open("POST",a,!1);d.send(c);return{status:d.status,responseText:d.responseText}}};